name: my-app
on: [push]
jobs:
	build:
		name: build
		runs-on: ubuntu-latest
		steps: 
			- name: checkout
			  uses: actions/checkout@v4
			- name: setup jdk-17
			  uses: action/setup-java@v1
			  with: 
				java-version: 17
			- name: build project with maven
			  run: mvn -B package --file pom.xml