name: my-app
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup jdk-17
        uses: actions/setup-java@v1
        with: 
          java-version: 17

      - name: setup chromedriver
        uses: browser-actions/setup-chrome@latest

      - name: check chrome version
        run: chrome --version

      - name: setup selenium dependencies
        run: |
          echo '<dependencies>
                  <dependency>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-java</artifactId>
                    <version>4.27.0</version>
                  </dependency>
                </dependencies>' > pom.xml
      
      - name: build project with maven and testng
        run: mvn -B clean test

      - name: check testng results
        run: cat target/surefire-reports/testng-results.xml
